version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: leetlab-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nitttiinn
      POSTGRES_PASSWORD: 123454321
      POSTGRES_DB: nitttiinn
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
